name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - name: Setup EC-CUBE
      env:
        PLUGIN_CODE: Square42
        PLUGIN_NAME: ec-cube/square42
        SQUARE_ENVIRONMENT: ${{ secrets.SQUARE_ENVIRONMENT }}
        SQUARE_APPLICATION_ID: ${{ secrets.SQUARE_APPLICATION_ID }}
        SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
        SQUARE_LOCATION_ID: ${{ secrets.SQUARE_LOCATION_ID }}
      run: docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d
    - name: Install dependencies
      run: yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
